# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up dbt
      - name: Install dbt
        run: |
          pip install dbt-postgres

      # Wait for PostgreSQL service to be ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      # Run your Python script to load data to PostgreSQL
      - name: Load sales data into PostgreSQL
        run: |
          python load_data_to_postgres.py

      # Set up dbt project profile (local connection to the PostgreSQL service)
      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "default:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: cleo2030
      port: 5432
      dbname: sales
      schema: public
  target: dev" > ~/.dbt/profiles.yml

      # Run dbt models
      - name: Run dbt models
        run: |
          cd my_dbt_project
          dbt run
